"""initial schema

Creates the full schema from SPEC §3: four enum types and six tables.

Handwritten rather than autogenerated. The unique constraints here *are* the
correctness argument of this service, so they are stated explicitly and reviewed
like any other code (SPEC §6.1).

Revision ID: 0001
Revises:
Create Date: 2026-07-10
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# `create_type=False`: the types are created once, explicitly, in upgrade().
# Left to itself, `op.create_table` would emit CREATE TYPE on first use and then
# fail on the second table that references the same type.
_WEBHOOK_STATUS = postgresql.ENUM(
    "pending",
    "processing",
    "succeeded",
    "dead_lettered",
    name="webhook_status",
    create_type=False,
)
_ATTEMPT_OUTCOME = postgresql.ENUM(
    "succeeded",
    # Extends the enum in SPEC §3. FR-10 requires a stale event be "recorded as
    # superseded rather than applied", which none of the spec's three values can
    # express. Introduced here because ALTER TYPE ... ADD VALUE cannot run inside
    # a transaction block on older Postgres. See docs/adr/0006.
    "superseded",
    "retryable_error",
    "non_retryable_error",
    name="attempt_outcome",
    create_type=False,
)
_DLQ_STATUS = postgresql.ENUM(
    "needs_review",
    "replaying",
    "resolved",
    "discarded",
    name="dlq_status",
    create_type=False,
)
_REPLAY_OUTCOME = postgresql.ENUM(
    "succeeded",
    "skipped_already_processed",
    "failed",
    name="replay_outcome",
    create_type=False,
)

_ENUMS = (_WEBHOOK_STATUS, _ATTEMPT_OUTCOME, _DLQ_STATUS, _REPLAY_OUTCOME)


def upgrade() -> None:
    bind = op.get_bind()
    for enum in _ENUMS:
        enum.create(bind, checkfirst=False)

    # --- webhook_event: the durable record of an accepted delivery -----------
    op.create_table(
        "webhook_event",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("external_id", sa.Text(), nullable=False),
        sa.Column("idempotency_key", sa.Text(), nullable=False),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.Column("entity_type", sa.Text(), nullable=False),
        sa.Column("entity_id", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(), nullable=False),
        sa.Column("headers", postgresql.JSONB(), nullable=False),
        sa.Column("signature_verified", sa.Boolean(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("provider_sequence", sa.BigInteger(), nullable=True),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("status", _WEBHOOK_STATUS, server_default="pending", nullable=False),
        sa.Column("attempt_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "next_attempt_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_webhook_event"),
        # FR-5. The deduplication guarantee. A redelivery loses the race here,
        # atomically, instead of in a SELECT-then-INSERT in Python.
        sa.UniqueConstraint(
            "source", "idempotency_key", name="uq_webhook_event_source_idempotency_key"
        ),
        sa.CheckConstraint("attempt_count >= 0", name="attempt_count_non_negative"),
    )
    # FR-7. Serves the worker poll predicate for both first attempts and retries:
    #   WHERE status = 'pending' AND next_attempt_at <= now()
    op.create_index(
        "ix_webhook_event_status_next_attempt_at",
        "webhook_event",
        ["status", "next_attempt_at"],
    )
    op.create_index(
        "ix_webhook_event_entity_type_entity_id",
        "webhook_event",
        ["entity_type", "entity_id"],
    )

    # --- processing_attempt: one row per worker pass --------------------------
    op.create_table(
        "processing_attempt",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("event_id", sa.BigInteger(), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("outcome", _ATTEMPT_OUTCOME, nullable=True),
        sa.Column("error_class", sa.Text(), nullable=True),
        sa.Column("error_detail", sa.Text(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_processing_attempt"),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["webhook_event.id"],
            name="fk_processing_attempt_event_id_webhook_event",
            ondelete="CASCADE",
        ),
        sa.UniqueConstraint(
            "event_id", "attempt_number", name="uq_processing_attempt_event_id_attempt_number"
        ),
        sa.CheckConstraint("attempt_number >= 1", name="attempt_number_positive"),
    )
    op.create_index("ix_processing_attempt_event_id", "processing_attempt", ["event_id"])

    # --- dead_letter_entry: FR-14, FR-15 -------------------------------------
    op.create_table(
        "dead_letter_entry",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("event_id", sa.BigInteger(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("attempts_made", sa.Integer(), nullable=False),
        sa.Column(
            "dead_lettered_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("status", _DLQ_STATUS, server_default="needs_review", nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolution_note", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_dead_letter_entry"),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["webhook_event.id"],
            name="fk_dead_letter_entry_event_id_webhook_event",
            ondelete="CASCADE",
        ),
        # One DLQ entry per event: re-dead-lettering must not fan out rows.
        sa.UniqueConstraint("event_id", name="uq_dead_letter_entry_event_id"),
        sa.CheckConstraint("attempts_made >= 0", name="attempts_made_non_negative"),
    )
    op.create_index("ix_dead_letter_entry_status", "dead_letter_entry", ["status"])

    # --- replay_request: FR-16 audit trail ------------------------------------
    op.create_table(
        "replay_request",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("event_id", sa.BigInteger(), nullable=False),
        sa.Column("requested_by", sa.Text(), nullable=False),
        sa.Column(
            "requested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("outcome", _REPLAY_OUTCOME, nullable=True),
        sa.Column("resulting_attempt_id", sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_replay_request"),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["webhook_event.id"],
            name="fk_replay_request_event_id_webhook_event",
            ondelete="CASCADE",
        ),
        # SET NULL, not CASCADE: purging attempt rows must not erase the record
        # that a human asked for a replay.
        sa.ForeignKeyConstraint(
            ["resulting_attempt_id"],
            ["processing_attempt.id"],
            name="fk_replay_request_resulting_attempt_id_processing_attempt",
            ondelete="SET NULL",
        ),
    )
    op.create_index("ix_replay_request_event_id", "replay_request", ["event_id"])

    # --- account: the demo entity; `version` backs the FR-10 optimistic guard --
    op.create_table(
        "account",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("external_ref", sa.Text(), nullable=False),
        sa.Column("balance_minor", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("version", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="pk_account"),
        sa.UniqueConstraint("external_ref", name="uq_account_external_ref"),
        sa.CheckConstraint("version >= 0", name="version_non_negative"),
    )

    # --- ledger_entry: the business effect. FR-6. -----------------------------
    op.create_table(
        "ledger_entry",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("account_id", sa.BigInteger(), nullable=False),
        sa.Column("event_id", sa.BigInteger(), nullable=False),
        sa.Column("amount_minor", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="pk_ledger_entry"),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["account.id"],
            name="fk_ledger_entry_account_id_account",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["webhook_event.id"],
            name="fk_ledger_entry_event_id_webhook_event",
            ondelete="CASCADE",
        ),
        # FR-6 / NFR-1. Reprocessing an event raises a unique violation here
        # rather than moving money twice. The load test asserts
        # count(ledger_entry) == count(distinct events) against this constraint.
        sa.UniqueConstraint("event_id", name="uq_ledger_entry_event_id"),
    )
    op.create_index("ix_ledger_entry_account_id", "ledger_entry", ["account_id"])


def downgrade() -> None:
    op.drop_table("ledger_entry")
    op.drop_table("account")
    op.drop_table("replay_request")
    op.drop_table("dead_letter_entry")
    op.drop_table("processing_attempt")
    op.drop_table("webhook_event")

    bind = op.get_bind()
    for enum in reversed(_ENUMS):
        enum.drop(bind, checkfirst=False)
